disabled_rules:
  - trailing_whitespace
  - file_length

opt_in_rules:
  - force_unwrapping
  - todo
  - cyclomatic_complexity

analyzer_rules:
  - unused_import

line_length:
  warning: 140
  error: 200

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - xs
    - sm
    - md
    - lg
    - xl
    - xxl
    - xxxl
    - on
    - id

excluded:
  - Daylight/Assets.xcassets
  - docs
  - tmp
  - app store
  - Daylight/Resources
